import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Banner from "../Components/Banner/Banner";
import Footer from "../Components/Footer/Footer";
import Navbar from "../Components/Navbar/Navbar";
import Post from "../Components/Post";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Banner></Banner>
      {posts.map((post) => (
        <div className="card mt-10 my-10 mx-10 bg-base-100 shadow-xl">
          <div className="card-body items-center text-center">
            <h2 className="card-title">Shoes!</h2>
            <p>If a dog chews shoes whose shoes does he choose?</p>
            <div className="card-actions"></div>
          </div>
        </div>
      ))}
      <Link href={`/posts`} className="flex justify-center items-center">
        <button className="btn btn-primary mb-10">See All</button>
      </Link>
      <Footer></Footer>
    </>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    "https://jsonplaceholder.typicode.com/posts?_limit=3"
  );
  const data = await res.json();

  return {
    props: {
      posts: data,
    },
  };
};
